import type { Product, ProductColor } from "@/lib/types";

const inkBlack: ProductColor = { name: "Negro desteñido", hex: "#1c1712" };
const agedCream: ProductColor = { name: "Crema envejecida", hex: "#e7d9b8" };
const oxideRust: ProductColor = { name: "Óxido", hex: "#a8452a" };
const washedDenim: ProductColor = { name: "Azul lavado", hex: "#3c4a5c" };

const tourTeeSizes: Product["sizes"] = ["S", "M", "L", "XL", "XXL"];

const standardDetails = [
  "Algodón pesado 240 g/m², percha ancha",
  "Serigrafía envejecida con lavado ácido",
  "Corte unisex clásico de los 80/90",
  "Tirada limitada — no se reimprime",
];

const lifestyleDetails = [
  "Algodón peinado 220 g/m², tacto suave",
  "Estampado digital de alta resolución",
  "Corte unisex regular",
  "Edición limitada numerada",
];

export const products: Product[] = [
  {
    id: "p1",
    slug: "tour-87-black-orchard",
    name: "Camiseta Tour '87",
    band: "Black Orchard",
    tourYear: "1987",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.6,
    reviewCount: 30,
    purchases: 320,
    description:
      "Réplica de la camiseta de gira de Black Orchard, temporada '87. Estampado craquelado como si hubiera sobrevivido treinta años en el fondo de un armario.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "skull",
    artworkImage: "/artwork/skull.png",
    tagline: "GROWN FROM ASHES",
    logoStyle: { tracking: "wide", decoration: "bar-both", accent: "†", accentColor: "#c9469b" },
    tourDates: [
      { city: "Cleveland, OH", date: "02 Mar" },
      { city: "Detroit, MI", date: "06 Mar" },
      { city: "Chicago, IL", date: "11 Mar" },
      { city: "Pittsburgh, PA", date: "17 Mar" },
      { city: "Buffalo, NY", date: "22 Mar" },
    ],
    featured: true,
  },
  {
    id: "p2",
    slug: "everglades-serpent",
    name: "Everglades",
    band: "EVERGLADES",
    tourYear: "N.10",
    editionLabel: "Colección",
    price: 29.9,
    compareAtPrice: 37.9,
    rating: 4.8,
    reviewCount: 74,
    purchases: 760,
    description:
      "Camiseta de la colección Horizonte. Una serpiente enroscada para quien prefiere el pantano a la ciudad.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, agedCream],
    graphic: "serpent",
    artworkImage: "/artwork/serpent.png",
    tagline: "WHERE THE BEASTS AND NATURE LIVE",
    logoStyle: { tracking: "normal", skew: -6, decoration: "none", accent: "◆", accentColor: "#8fd13b" },
    tourDates: [],
    featured: true,
  },
  {
    id: "p3",
    slug: "dust-bowl-prophets-revival",
    name: "Revival Tour",
    band: "Dust Bowl Prophets",
    tourYear: "1979",
    price: 26.5,
    compareAtPrice: 33.9,
    rating: 4.5,
    reviewCount: 19,
    purchases: 210,
    description:
      "La camiseta de la gira de reavivamiento de Dust Bowl Prophets. Grafismo de cruz desgastada y tipografía de cartel de carretera.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack, washedDenim],
    graphic: "cross",
    artworkImage: "/artwork/cross.png",
    tagline: "SAVED BY THE SOUND",
    logoStyle: { tracking: "wider", decoration: "bar-under", accent: "✦", accentColor: "#e0a72b" },
    tourDates: [
      { city: "Tulsa, OK", date: "01 Sep" },
      { city: "Wichita, KS", date: "05 Sep" },
      { city: "Amarillo, TX", date: "10 Sep" },
      { city: "Albuquerque, NM", date: "15 Sep" },
      { city: "Phoenix, AZ", date: "21 Sep" },
    ],
    featured: true,
    isNew: true,
  },
  {
    id: "p4",
    slug: "coyote-wire-static",
    name: "Static",
    band: "Coyote Wire",
    tourYear: "1995",
    price: 28.9,
    compareAtPrice: 36.9,
    rating: 4.5,
    reviewCount: 16,
    purchases: 180,
    description:
      "Diseño inspirado en la portada de 'Static' de Coyote Wire. Rayo estampado a mano, colorido apagado por el sol.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "bolt",
    artworkImage: "/artwork/bolt.png",
    tagline: "STRUCK NOT STIRRED",
    logoStyle: { tracking: "tight", skew: 8, decoration: "none", accent: "⚡", accentColor: "#33c6f4" },
    tourDates: [
      { city: "Portland, OR", date: "03 Oct" },
      { city: "Seattle, WA", date: "06 Oct" },
      { city: "Boise, ID", date: "10 Oct" },
      { city: "Salt Lake City, UT", date: "14 Oct" },
      { city: "Denver, CO", date: "19 Oct" },
    ],
  },
  {
    id: "p5",
    slug: "hollow-saints-midnight-mass",
    name: "Midnight Mass",
    band: "Hollow Saints",
    tourYear: "1983",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.6,
    reviewCount: 23,
    purchases: 245,
    description:
      "Camiseta de la gira 'Midnight Mass' de Hollow Saints. Luna gótica sobre algodón desteñido, para las últimas filas del concierto.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "moon",
    artworkImage: "/artwork/moon.png",
    tagline: "SINNERS AFTER DARK",
    logoStyle: { tracking: "normal", decoration: "bar-over", accent: "✶", accentColor: "#7ec8e3" },
    tourDates: [
      { city: "Providence, RI", date: "01 Nov" },
      { city: "Boston, MA", date: "04 Nov" },
      { city: "Hartford, CT", date: "08 Nov" },
      { city: "Albany, NY", date: "12 Nov" },
      { city: "Syracuse, NY", date: "16 Nov" },
    ],
    isNew: true,
  },
  {
    id: "p6",
    slug: "iron-magnolia-southbound",
    name: "Southbound",
    band: "Iron Magnolia",
    tourYear: "1989",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.6,
    reviewCount: 26,
    purchases: 280,
    description:
      "Alas oxidadas y letras resquebrajadas para la gira 'Southbound' de Iron Magnolia. Un clásico de mercadillo de discos.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, agedCream],
    graphic: "wings",
    artworkImage: "/artwork/wings.png",
    tagline: "RUST NEVER DIES",
    logoStyle: { tracking: "wide", skew: -3, decoration: "none", accent: "✧", accentColor: "#d9662b" },
    tourDates: [
      { city: "Nashville, TN", date: "02 Abr" },
      { city: "Birmingham, AL", date: "06 Abr" },
      { city: "Jackson, MS", date: "10 Abr" },
      { city: "Baton Rouge, LA", date: "14 Abr" },
      { city: "Mobile, AL", date: "18 Abr" },
    ],
    featured: true,
  },
  {
    id: "p7",
    slug: "midnight-combine-harvest-of-noise",
    name: "Harvest Of Noise",
    band: "Midnight Combine",
    tourYear: "1997",
    price: 45.0,
    compareAtPrice: 56.9,
    rating: 4.5,
    reviewCount: 13,
    purchases: 150,
    description:
      "Sudadera pesada de la gira 'Harvest Of Noise'. Interior perchado, estampado envejecido a juego con la camiseta original.",
    details: [
      "Algodón/poliéster 320 g/m², interior perchado",
      "Serigrafía envejecida con lavado ácido",
      "Corte oversize unisex",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "flame",
    artworkImage: "/artwork/flame.png",
    tagline: "BORN OF THE FIRE",
    logoStyle: { tracking: "normal", skew: -4, decoration: "bar-under", accent: "‡", accentColor: "#e8452c" },
    tourDates: [
      { city: "Des Moines, IA", date: "02 Ago" },
      { city: "Omaha, NE", date: "06 Ago" },
      { city: "Kansas City, MO", date: "10 Ago" },
      { city: "St. Louis, MO", date: "15 Ago" },
      { city: "Louisville, KY", date: "20 Ago" },
    ],
  },
  {
    id: "p8",
    slug: "gravel-glory-open-road",
    name: "Open Road",
    band: "Gravel & Glory",
    tourYear: "1985",
    price: 45.0,
    compareAtPrice: 56.9,
    rating: 4.4,
    reviewCount: 11,
    purchases: 120,
    description:
      "Sudadera de carretera de Gravel & Glory. Estrella descentrada al pecho, como la que llevaba el roadie en la última fila del bus.",
    details: [
      "Algodón/poliéster 320 g/m², interior perchado",
      "Serigrafía envejecida con lavado ácido",
      "Corte oversize unisex",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, agedCream],
    graphic: "star",
    artworkImage: "/artwork/star.png",
    tagline: "CHASING THE HORIZON",
    logoStyle: { tracking: "wide", decoration: "bar-both", accent: "★", accentColor: "#f2c14e" },
    tourDates: [
      { city: "Reno, NV", date: "01 May" },
      { city: "Sacramento, CA", date: "05 May" },
      { city: "Fresno, CA", date: "09 May" },
      { city: "Bakersfield, CA", date: "13 May" },
      { city: "San Diego, CA", date: "18 May" },
    ],
    isNew: true,
  },
  {
    id: "p9",
    slug: "rustbelt-choir-patch",
    name: "Parche bordado",
    band: "The Rustbelt Choir",
    tourYear: "1992",
    price: 9.9,
    compareAtPrice: 13.9,
    rating: 4.4,
    reviewCount: 9,
    purchases: 95,
    description:
      "Parche bordado de The Rustbelt Choir para chupa o mochila. Termoadhesivo, con borde de sarga envejecido.",
    details: [
      "Bordado 100% hilo de poliéster",
      "Base termoadhesiva + 2 ojales para coser",
      "8.5 cm de diámetro",
      "Tirada limitada — no se reimprime",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "dove",
    artworkImage: "/artwork/dove.png",
    tagline: "SING THROUGH THE STATIC",
    logoStyle: { tracking: "normal", decoration: "none", accent: "§", accentColor: "#6fa8c9" },
    tourDates: [
      { city: "Gary, IN", date: "10 Ene" },
      { city: "Toledo, OH", date: "14 Ene" },
      { city: "Akron, OH", date: "18 Ene" },
      { city: "Youngstown, OH", date: "22 Ene" },
      { city: "Erie, PA", date: "26 Ene" },
    ],
  },
  {
    id: "p10",
    slug: "rattlesnake-kings-scorched-earth",
    name: "Scorched Earth",
    band: "Rattlesnake Kings",
    tourYear: "1988",
    price: 28.5,
    compareAtPrice: 35.9,
    rating: 4.8,
    reviewCount: 66,
    purchases: 690,
    description:
      "Camiseta de la gira 'Scorched Earth' de Rattlesnake Kings. Escorpión al acecho estampado en tinta única, para las noches más calurosas del desierto.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, agedCream],
    graphic: "scorpion",
    artworkImage: "/artwork/scorpion.png",
    tagline: "STING FIRST, ASK LATER",
    logoStyle: { tracking: "wide", skew: 4, decoration: "bar-under", accent: "◈", accentColor: "#c9d92b" },
    tourDates: [
      { city: "Tucson, AZ", date: "02 Jul" },
      { city: "Yuma, AZ", date: "06 Jul" },
      { city: "Palm Springs, CA", date: "10 Jul" },
      { city: "Las Cruces, NM", date: "15 Jul" },
      { city: "El Paso, TX", date: "20 Jul" },
    ],
    isNew: true,
  },
  {
    id: "p11",
    slug: "imagine-the-world-clouds",
    name: "Imagine The World",
    band: "IMAGINE THE WORLD",
    tourYear: "N.01",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 48,
    purchases: 505,
    description:
      "Camiseta de la colección Horizonte. Un cielo real, colinas verdes y una frase que dice todo lo que hace falta.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/clouds.png",
    tagline: "ONE SKY, ONE EARTH",
    logoStyle: { tracking: "wide", decoration: "none", accent: "☁", accentColor: "#4fa8d8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p12",
    slug: "nothing-like-home-cottage",
    name: "Nothing Like Home",
    band: "NOTHING LIKE HOME",
    tourYear: "N.02",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 53,
    purchases: 560,
    description:
      "Camiseta de la colección Horizonte. Una casita de campo inglesa, jardín florido y ganas de quedarse en casa.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, oxideRust, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/cottage.png",
    tagline: "EAST, WEST, HOME'S BEST",
    logoStyle: { tracking: "wide", decoration: "none", accent: "⌂", accentColor: "#c98a3e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p13",
    slug: "chase-the-horizon-mountains",
    name: "Chase The Horizon",
    band: "CHASE THE HORIZON",
    tourYear: "N.03",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.8,
    reviewCount: 92,
    purchases: 940,
    description:
      "Camiseta de la colección Horizonte. Una cordillera al atardecer para quien nunca deja de mirar más allá.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/mountains.png",
    tagline: "NEVER STOP EXPLORING",
    logoStyle: { tracking: "wide", decoration: "none", accent: "▲", accentColor: "#e8752c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p14",
    slug: "slow-down-breathe-beach",
    name: "Slow Down, Breathe",
    band: "SLOW DOWN, BREATHE",
    tourYear: "N.04",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 39,
    purchases: 410,
    description:
      "Camiseta de la colección Horizonte. Palmeras, atardecer y el recordatorio de que no pasa nada por ir más despacio.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/beach.png",
    tagline: "PARADISE FOUND",
    logoStyle: { tracking: "wide", decoration: "none", accent: "☀", accentColor: "#f2a03d" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p15",
    slug: "made-for-the-night-skyline",
    name: "Made For The Night",
    band: "MADE FOR THE NIGHT",
    tourYear: "N.05",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.6,
    reviewCount: 43,
    purchases: 455,
    description:
      "Camiseta de la colección Horizonte. Rascacielos, reflejos en el agua y esa energía que solo tiene la ciudad de noche.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/skyline.png",
    tagline: "CITY LIGHTS, CLEAR MIND",
    logoStyle: { tracking: "wide", decoration: "none", accent: "✦", accentColor: "#6fa8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p16",
    slug: "take-the-long-way-roadtrip",
    name: "Take The Long Way",
    band: "TAKE THE LONG WAY",
    tourYear: "N.06",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.6,
    reviewCount: 34,
    purchases: 365,
    description:
      "Camiseta de la colección Horizonte. Una furgoneta, una carretera del desierto y ninguna prisa por llegar.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/roadtrip.png",
    tagline: "DESERT HIGHWAY DREAMS",
    logoStyle: { tracking: "wide", decoration: "none", accent: "➤", accentColor: "#d9793f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p17",
    slug: "answer-the-call-wolf",
    name: "Answer The Call",
    band: "HOWL",
    tourYear: "N.07",
    editionLabel: "Colección",
    price: 26.9,
    compareAtPrice: 33.9,
    rating: 5.0,
    reviewCount: 156,
    purchases: 1420,
    description:
      "Camiseta insignia de la colección Horizonte. Un lobo, la luna y las montañas — la escena que le da nombre a todo esto.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/wolfmoon.png",
    tagline: "ANSWER THE CALL",
    logoStyle: { tracking: "wide", decoration: "none", accent: "☾", accentColor: "#9aa0a6" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p18",
    slug: "swamp-crocodile",
    name: "Swamp",
    band: "SWAMP",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 121,
    purchases: 1180,
    description:
      "Camiseta de la colección Horizonte. Un cocodrilo asomando junto al muelle, un pescador que no se entera de nada — al pecho, solo el cocodrilo.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/croc_chest.png",
    backArtworkImage: "/artwork/croc_lake.png",
    frontLogoOnly: true,
    tagline: "PATIENCE PAYS OFF",
    logoStyle: { tracking: "wide", decoration: "none", accent: "≈", accentColor: "#7a9a3f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p19",
    slug: "wild-west-cowboy",
    name: "Wild West",
    band: "WILD WEST",
    tourYear: "N.09",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 103,
    purchases: 1050,
    description:
      "Camiseta de la colección Horizonte. Un jinete a galope y una frase para los días cuesta arriba.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/cowboy.png",
    tagline: "HARD TIMES BUILD HARD MEN",
    logoStyle: { tracking: "wide", decoration: "none", accent: "★", accentColor: "#4a7ab8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p20",
    slug: "ufo-obsession",
    name: "UFO Obsession",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.7,
    reviewCount: 58,
    purchases: 615,
    description:
      "Camiseta de la colección Horizonte. Un alienígena discreto al pecho, la abducción de una vaca de campo detrás — para quien cree que no estamos solos.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_chest.png",
    backArtworkImage: "/artwork/ufo_scene.png",
    frontLogoOnly: true,
    tagline: "WE ARE NOT ALONE",
    logoStyle: { tracking: "wide", decoration: "none", accent: "✦", accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p21",
    slug: "tradition-innovation-crane",
    name: "Tradition & Innovation",
    band: "伝統と革新",
    tourYear: "",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.9,
    reviewCount: 79,
    purchases: 810,
    description:
      "Camiseta de la colección Horizonte. Una grulla sobre una gran ola, tinta tradicional japonesa sobre algodón.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/japan_crane.png",
    tagline: "TRADITION MEETS INNOVATION",
    logoStyle: { tracking: "wide", decoration: "none", accent: "波", accentColor: "#c9463e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p22",
    slug: "camel-desert",
    name: "Camel",
    band: "CAMEL",
    tourYear: "N.11",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.6,
    reviewCount: 10,
    description:
      "Camiseta de la colección Horizonte. Un camello ornamentado frente a la puesta de sol del desierto.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/camel.png",
    tagline: "RELENTLESS IN THE DESERT",
    logoStyle: { tracking: "wide", decoration: "none", accent: "☉", accentColor: "#d9a441" },
    tourDates: [],
    isNew: true,
  },
];

export function getAllProducts(): Product[] {
  return products;
}

// Orden curado a mano por atractivo/potencial de venta, de más a menos.
const FEATURED_ORDER = [
  "answer-the-call-wolf",
  "swamp-crocodile",
  "wild-west-cowboy",
  "chase-the-horizon-mountains",
  "everglades-serpent",
  "rattlesnake-kings-scorched-earth",
  "nothing-like-home-cottage",
  "tour-87-black-orchard",
];

export function getNewProducts(limit = 8): Product[] {
  return products
    .filter((p) => p.isNew)
    .slice()
    .reverse()
    .slice(0, limit);
}

export function getFeaturedProducts(): Product[] {
  return FEATURED_ORDER.map((slug) => products.find((p) => p.slug === slug)).filter(
    (p): p is Product => Boolean(p)
  );
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return products
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function getCategories(): Product["category"][] {
  return Array.from(new Set(products.map((p) => p.category)));
}
