import type { Product, ProductColor } from "@/lib/types";

const inkBlack: ProductColor = { name: "Negro desteñido", hex: "#1c1712" };
const agedCream: ProductColor = { name: "Crema envejecida", hex: "#e7d9b8" };
const oxideRust: ProductColor = { name: "Óxido", hex: "#a8452a" };
const washedDenim: ProductColor = { name: "Azul lavado", hex: "#3c4a5c" };
const sunYellow: ProductColor = { name: "Amarillo cereza", hex: "#e0b23c" };

const tourTeeSizes: Product["sizes"] = ["S", "M", "L", "XL", "XXL"];

const standardDetails = [
  "Algodón pesado 240 g/m², percha ancha",
  "Serigrafía envejecida con lavado ácido",
  "Corte unisex clásico de los 80/90",
  "Tirada limitada — no se reimprime",
];

const lifestyleDetails = [
  "Algodón peinado 220 g/m², tacto suave",
  "Estampado digital de alta resolución",
  "Corte unisex regular",
  "Edición limitada numerada",
];

export const products: Product[] = [
  {
    id: "p2",
    slug: "everglades-serpent",
    name: "Everglades",
    band: "EVERGLADES",
    tourYear: "N.10",
    editionLabel: "Colección",
    price: 29.9,
    compareAtPrice: 37.9,
    rating: 4.8,
    reviewCount: 74,
    purchases: 760,
    description:
      "Camiseta de la colección Horizonte. Una serpiente enroscada para quien prefiere el pantano a la ciudad.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, agedCream],
    graphic: "serpent",
    artworkImage: "/artwork/serpent.png",
    tagline: "WHERE THE BEASTS AND NATURE LIVE",
    logoStyle: { skew: -6, accentColor: "#8fd13b" },
    tourDates: [],
    backHeroPhoto: "herotop-everglades-serpent",
  },
  {
    id: "p4",
    slug: "coyote-wire-static",
    name: "Static",
    band: "Coyote Wire",
    tourYear: "1995",
    price: 28.9,
    compareAtPrice: 36.9,
    rating: 4.5,
    reviewCount: 16,
    purchases: 180,
    description:
      "Diseño inspirado en la portada de 'Static' de Coyote Wire. Rayo estampado a mano, colorido apagado por el sol.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "bolt",
    artworkImage: "/artwork/bolt.png",
    tagline: "STRUCK NOT STIRRED",
    logoStyle: { skew: 8, accentColor: "#33c6f4" },
    tourDates: [
      { city: "Portland, OR", date: "03 Oct" },
      { city: "Seattle, WA", date: "06 Oct" },
      { city: "Boise, ID", date: "10 Oct" },
      { city: "Salt Lake City, UT", date: "14 Oct" },
      { city: "Denver, CO", date: "19 Oct" },
    ],
  },
  {
    id: "p5",
    slug: "hollow-saints-midnight-mass",
    name: "Midnight Mass",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.6,
    reviewCount: 23,
    purchases: 245,
    description:
      "Camiseta de la colección Horizonte. La luna duerme con gorro y manta al pecho — para quien también se queda despierto pensando en nada a las tres de la mañana.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "moon",
    artworkImage: "/artwork/moon.png",
    frontLogoOnly: true,
    backHeroPhoto: "moon-back-black",
    tagline: "STILL AWAKE. STILL NORMAL.",
    logoStyle: { accentColor: "#7ec8e3" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p6",
    slug: "iron-magnolia-southbound",
    name: "Southbound",
    band: "Iron Magnolia",
    tourYear: "1989",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.6,
    reviewCount: 26,
    purchases: 280,
    description:
      "Alas oxidadas y letras resquebrajadas para la gira 'Southbound' de Iron Magnolia. Un clásico de mercadillo de discos.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "wings",
    artworkImage: "/artwork/wings.png",
    tagline: "RUST NEVER DIES",
    logoStyle: { skew: -3, accentColor: "#d9662b" },
    tourDates: [
      { city: "Nashville, TN", date: "02 Abr" },
      { city: "Birmingham, AL", date: "06 Abr" },
      { city: "Jackson, MS", date: "10 Abr" },
      { city: "Baton Rouge, LA", date: "14 Abr" },
      { city: "Mobile, AL", date: "18 Abr" },
    ],
  },
  {
    id: "p7",
    slug: "midnight-combine-harvest-of-noise",
    name: "Harvest Of Noise",
    band: "Midnight Combine",
    tourYear: "1997",
    price: 45.0,
    compareAtPrice: 56.9,
    rating: 4.5,
    reviewCount: 13,
    purchases: 150,
    description:
      "Sudadera con capucha de algodón pesado. Llama pequeña al pecho con el HOWL escondido dentro — interior perchado, sin nada a la espalda.",
    details: [
      "Algodón/poliéster 320 g/m², interior perchado",
      "Serigrafía envejecida con lavado ácido",
      "Corte oversize unisex",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "flame",
    artworkImage: "/artwork/flame.png",
    backHeroPhoto: "hoodie-back-black",
    frontLogoOnly: true,
    logoStyle: { skew: -4, accentColor: "#e8452c" },
    tourDates: [
      { city: "Des Moines, IA", date: "02 Ago" },
      { city: "Omaha, NE", date: "06 Ago" },
      { city: "Kansas City, MO", date: "10 Ago" },
      { city: "St. Louis, MO", date: "15 Ago" },
      { city: "Louisville, KY", date: "20 Ago" },
    ],
  },
  {
    id: "p10",
    slug: "rattlesnake-kings-scorched-earth",
    name: "Scorched Earth",
    band: "Rattlesnake Kings",
    tourYear: "1988",
    price: 28.5,
    compareAtPrice: 35.9,
    rating: 4.8,
    reviewCount: 66,
    purchases: 690,
    description:
      "Camiseta de la gira 'Scorched Earth' de Rattlesnake Kings. Escorpión al acecho estampado en tinta única, para las noches más calurosas del desierto.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, agedCream],
    graphic: "scorpion",
    artworkImage: "/artwork/scorpion.png",
    tagline: "STING FIRST, ASK LATER",
    logoStyle: { skew: 4, accentColor: "#c9d92b" },
    tourDates: [
      { city: "Tucson, AZ", date: "02 Jul" },
      { city: "Yuma, AZ", date: "06 Jul" },
      { city: "Palm Springs, CA", date: "10 Jul" },
      { city: "Las Cruces, NM", date: "15 Jul" },
      { city: "El Paso, TX", date: "20 Jul" },
    ],
    isNew: true,
    backHeroPhoto: "herotop-rattlesnake-kings-scorched-earth",
  },
  {
    id: "p11",
    slug: "imagine-the-world-clouds",
    name: "Imagine The World",
    band: "IMAGINE THE WORLD",
    tourYear: "N.01",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 48,
    purchases: 505,
    description:
      "Camiseta de la colección Horizonte. Un cielo real, colinas verdes y una frase que dice todo lo que hace falta.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/clouds.png",
    tagline: "ONE SKY, ONE EARTH",
    logoStyle: { accentColor: "#4fa8d8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p12",
    slug: "nothing-like-home-cottage",
    name: "Nothing Like Home",
    band: "NOTHING LIKE HOME",
    tourYear: "N.02",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 53,
    purchases: 560,
    description:
      "Camiseta de la colección Horizonte. Una casita de campo inglesa, jardín florido y ganas de quedarse en casa.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, oxideRust, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/cottage.png",
    tagline: "EAST, WEST, HOME'S BEST",
    logoStyle: { accentColor: "#c98a3e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p13",
    slug: "chase-the-horizon-mountains",
    name: "Chase The Horizon",
    band: "CHASE THE HORIZON",
    tourYear: "N.03",
    editionLabel: "Colección",
    price: 26.9,
    compareAtPrice: 33.9,
    rating: 4.8,
    reviewCount: 92,
    purchases: 940,
    description:
      "Camiseta de la colección Horizonte. Una cordillera al atardecer para quien nunca deja de mirar más allá.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/mountains.png",
    tagline: "NEVER STOP EXPLORING",
    logoStyle: { accentColor: "#e8752c" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "herotop-chase-the-horizon-mountains",
  },
  {
    id: "p14",
    slug: "slow-down-breathe-beach",
    name: "Slow Down, Breathe",
    band: "SLOW DOWN, BREATHE",
    tourYear: "N.04",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 39,
    purchases: 410,
    description:
      "Camiseta de la colección Horizonte. Palmeras, atardecer y el recordatorio de que no pasa nada por ir más despacio.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/beach.png",
    tagline: "PARADISE FOUND",
    logoStyle: { accentColor: "#f2a03d" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p15",
    slug: "made-for-the-night-skyline",
    name: "Made For The Night",
    band: "MADE FOR THE NIGHT",
    tourYear: "N.05",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.6,
    reviewCount: 43,
    purchases: 455,
    description:
      "Camiseta de la colección Horizonte. Rascacielos, reflejos en el agua y esa energía que solo tiene la ciudad de noche.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/skyline.png",
    tagline: "CITY LIGHTS, CLEAR MIND",
    logoStyle: { accentColor: "#6fa8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p16",
    slug: "take-the-long-way-roadtrip",
    name: "Take The Long Way",
    band: "TAKE THE LONG WAY",
    tourYear: "N.06",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.6,
    reviewCount: 34,
    purchases: 365,
    description:
      "Camiseta de la colección Horizonte. Una furgoneta, una carretera del desierto y ninguna prisa por llegar.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/roadtrip.png",
    tagline: "DESERT HIGHWAY DREAMS",
    logoStyle: { accentColor: "#d9793f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p17",
    slug: "answer-the-call-wolf",
    name: "Answer The Call",
    band: "HOWL",
    tourYear: "N.07",
    editionLabel: "Colección",
    price: 26.9,
    compareAtPrice: 33.9,
    rating: 5.0,
    reviewCount: 156,
    purchases: 1420,
    description:
      "Camiseta insignia de la colección Horizonte. Un lobo, la luna y las montañas — la escena que le da nombre a todo esto.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/wolfmoon.png",
    frontLogoOnly: true,
    tagline: "ANSWER THE CALL",
    logoStyle: { accentColor: "#9aa0a6" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "wolfmoon-back-black",
  },
  {
    id: "p18",
    slug: "swamp-crocodile",
    name: "Swamp",
    band: "SWAMP",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 121,
    purchases: 1180,
    description:
      "Camiseta de la colección Horizonte. Un cocodrilo asomando junto al muelle, un pescador que no se entera de nada — al pecho, solo el cocodrilo.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/croc_chest.png",
    backArtworkImage: "/artwork/croc_lake.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "PATIENCE PAYS OFF",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p19",
    slug: "wild-west-cowboy",
    name: "Wild West",
    band: "WILD WEST",
    tourYear: "N.09",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 103,
    purchases: 1050,
    description:
      "Camiseta de la colección Horizonte. Un jinete a galope y una frase para los días cuesta arriba.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/cowboy.png",
    logoStyle: { accentColor: "#4a7ab8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p20",
    slug: "ufo-obsession",
    name: "UFO Obsession",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.7,
    reviewCount: 58,
    purchases: 615,
    description:
      "Camiseta de la colección Horizonte. Un alienígena discreto al pecho, la abducción de una vaca de campo detrás — para quien cree que no estamos solos.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_chest.png",
    backArtworkImage: "/artwork/ufo_scene.png",
    frontLogoOnly: true,
    tagline: "WE ARE NOT ALONE",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "ufo_scene-black",
  },
  {
    id: "p21",
    slug: "tradition-innovation-crane",
    name: "Tradition & Innovation",
    band: "伝統と革新",
    tourYear: "",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.9,
    reviewCount: 79,
    purchases: 810,
    description:
      "Camiseta de la colección Horizonte. Una grulla sobre una gran ola, tinta tradicional japonesa sobre algodón.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/japan_crane.png",
    tagline: "TRADITION MEETS INNOVATION",
    logoStyle: { accentColor: "#c9463e" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "herotop-tradition-innovation-crane",
  },
  {
    id: "p22",
    slug: "camel-desert",
    name: "Camel",
    band: "CAMEL",
    tourYear: "N.11",
    editionLabel: "Colección",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.6,
    reviewCount: 10,
    description:
      "Camiseta de la colección Horizonte. Un camello ornamentado frente a la puesta de sol del desierto.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/camel.png",
    tagline: "RELENTLESS IN THE DESERT",
    logoStyle: { accentColor: "#d9a441" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p23",
    slug: "howl-project-basics",
    name: "Howl Project",
    band: "HOWL",
    backBand: "HOWL PROJECT",
    tourYear: "N.12",
    editionLabel: "Colección",
    price: 22.9,
    compareAtPrice: 28.9,
    rating: 4.5,
    reviewCount: 7,
    description:
      "Básica de la colección Horizonte. Solo tipografía, sin ilustración — para los días de \"menos es más\".",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/howl-wordmark.png",
    frontLogoOnly: true,
    textOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "howl-project-back",
  },
  {
    id: "p24",
    slug: "everything-is-fine",
    name: "Everything Is Fine",
    band: "EVERYTHING IS FINE",
    tourYear: "N.13",
    editionLabel: "Colección",
    price: 22.9,
    compareAtPrice: 28.9,
    rating: 4.5,
    reviewCount: 6,
    description:
      "Camiseta de la colección Horizonte. Una llama, un icono, y la calma de saber que todo va bien.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/flame_icon.png",
    logoStyle: { accentColor: "#e8752c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p25",
    slug: "raised-by-dragons",
    name: "Raised By Dragons",
    band: "RAISED BY DRAGONS",
    tourYear: "2024",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.7,
    reviewCount: 9,
    purchases: 140,
    description:
      "Camiseta de la colección Horizonte. Dragón pequeño al pecho, ilustración grande a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/dragon_chest.png",
    backArtworkImage: "/artwork/dragon_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "YEAR OF THE DRAGON",
    logoStyle: { accentColor: "#c9463e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p26",
    slug: "sunday-afternoon-route-66",
    name: "Sunday Afternoon",
    band: "SUNDAY AFTERNOON",
    backBand: "SUNDAY AFTERNOON",
    tourYear: "2024",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.8,
    reviewCount: 5,
    purchases: 60,
    description:
      "Camiseta de la colección Horizonte. Logo pequeño al pecho, gasolinera de Route 66 ilustrada a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/sunday_chest.png",
    backArtworkImage: "/artwork/sunday_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "FILL THE TANK FOR THE WEEK",
    logoStyle: { accentColor: "#4a7a9c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p27",
    slug: "nightfall-dive-hawk",
    name: "Nightfall Dive",
    band: "NIGHTFALL DIVE",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.6,
    reviewCount: 3,
    description:
      "Camiseta minimalista de la colección Horizonte. Un halcón en picado, línea fina, una tinta.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "wings",
    artworkImage: "/artwork/nightfall_dive.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p28",
    slug: "moth-flame",
    name: "Moth & Flame",
    band: "MOTH & FLAME",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.7,
    reviewCount: 4,
    description:
      "Camiseta minimalista de la colección Horizonte. Una polilla nocturna descendiendo hacia la llama.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "moon",
    artworkImage: "/artwork/moth_flame.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p29",
    slug: "lost-bearing-compass",
    name: "Lost Bearing",
    band: "LOST BEARING",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.5,
    reviewCount: 2,
    description:
      "Camiseta minimalista de la colección Horizonte. Una brújula vieja, mellada, aguja torcida.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "star",
    artworkImage: "/artwork/lost_bearing.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p30",
    slug: "cut-loose-anchor",
    name: "Cut Loose",
    band: "CUT LOOSE",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.8,
    reviewCount: 5,
    description:
      "Camiseta minimalista de la colección Horizonte. Un ancla y una cuerda deshilachada — desanclarse.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "cross",
    artworkImage: "/artwork/cut_loose.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p31",
    slug: "old-iron-helmet",
    name: "Old Iron",
    band: "OLD IRON",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.9,
    reviewCount: 6,
    description:
      "Camiseta minimalista de la colección Horizonte. Casco motero vintage con gafas de aviador.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, agedCream],
    graphic: "skull",
    artworkImage: "/artwork/old_iron.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p32",
    slug: "unbroken-knot",
    name: "Unbroken",
    band: "UNBROKEN",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.6,
    reviewCount: 3,
    description:
      "Camiseta minimalista de la colección Horizonte. Nudo marinero en figura de ocho — vínculo, lealtad.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "cross",
    artworkImage: "/artwork/unbroken.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p34",
    slug: "howl-vintage-wolf",
    name: "Vintage Howl",
    band: "HOWL",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 11,
    purchases: 210,
    description:
      "Camiseta de la colección Horizonte. Lobo aullando sobre roca, grabado vintage, tipografía stencil.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim],
    graphic: "moon",
    artworkImage: "/artwork/howl_wolf_vintage.png",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p35",
    slug: "stay-feral",
    name: "Stay Feral",
    band: "STAY FERAL",
    tourYear: "",
    price: 23.9,
    compareAtPrice: 29.9,
    rating: 4.5,
    reviewCount: 4,
    description:
      "Camiseta de la colección Horizonte. Tipografía brutalista, collage punk/fanzine.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, oxideRust],
    graphic: "bolt",
    artworkImage: "/artwork/stay_feral.png",
    textOnly: false,
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p36",
    slug: "love-is-a-long-road",
    name: "Love Is A Long Road",
    band: "LOVE IS A LONG ROAD",
    tourYear: "",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.7,
    reviewCount: 6,
    description:
      "Camiseta de la colección Horizonte. Muscle car de los 70 al atardecer, script retro.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/love_long_road_v2.png",
    logoStyle: { accentColor: "#d9793f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p37",
    slug: "blueprint-wolf",
    name: "Blueprint",
    band: "HOWL",
    tourYear: "N.01",
    editionLabel: "Especimen",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.8,
    reviewCount: 5,
    description:
      "Camiseta de la colección Horizonte. Cráneo de lobo en plano técnico, estilo patente antigua.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/blueprint_wolf.png",
    logoStyle: { accentColor: "#3c4a5c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p38",
    slug: "freedom-nyc",
    name: "Freedom",
    band: "NYC",
    backBand: "FREEDOM",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 7,
    description:
      "Camiseta de la colección Horizonte. Logo pequeño NYC al pecho, la Estatua de la Libertad grabada a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/nyc_chest.png",
    backArtworkImage: "/artwork/freedom_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p39",
    slug: "cherry-howl-supply-co",
    name: "Cherry Supply Co.",
    band: "HOWL SUPPLY CO.",
    tourYear: "MMXXIV",
    price: 24.9,
    compareAtPrice: 31.9,
    rating: 4.8,
    reviewCount: 6,
    description:
      "Camiseta amarilla de la colección Horizonte. Cerezas vintage y wordmark universitario en el pecho.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [sunYellow],
    graphic: "landscape",
    artworkImage: "/artwork/cherry_howl.png",
    logoStyle: { accentColor: "#a8231c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p40",
    slug: "howlers",
    name: "Howlers",
    band: "HOWLERS",
    backBand: "HOWLERS",
    tourYear: "2026",
    editionLabel: "Especial",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.8,
    reviewCount: 4,
    description:
      "Camiseta especial HOWL. Lobo en línea fina al pecho, la manada aullando junta en la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/howlers.png",
    backArtworkImage: "/artwork/howlers_pack.png",
    backTextBaked: true,
    logoStyle: { accentColor: "#1c1712" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p41",
    slug: "eternal-yinyang",
    name: "Eternal",
    band: "永恆",
    backBand: "永恆",
    tourYear: "",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.7,
    reviewCount: 3,
    description:
      "Camiseta de la colección Horizonte. Yin-yang pequeño al pecho, grande y con caligrafía china a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/eternal_chest.png",
    backArtworkImage: "/artwork/eternal_back.png",
    frontLogoOnly: true,
    backHeroPhoto: "eternal_back-denim",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p42",
    slug: "lunar-hotel",
    name: "Lunar Hotel",
    band: "HOWL",
    backBand: "LUNAR HOTEL",
    tourYear: "2047",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 5,
    description:
      "Camiseta de la colección Horizonte. Luna pequeña al pecho, hotel lunar retro-futurista a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/lunar_chest.png",
    backArtworkImage: "/artwork/lunar_back.png",
    frontLogoOnly: true,
    backHeroPhoto: "lunar_back-denim",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p43",
    slug: "sticker-alien",
    name: "Sticker Alien",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    rating: 4.9,
    reviewCount: 12,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_chest.png",
    photoOverride: "sticker-alien",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
  },
  {
    id: "p44",
    slug: "sticker-crocodile",
    name: "Sticker Crocodile",
    band: "SWAMP",
    tourYear: "",
    price: 5,
    rating: 4.8,
    reviewCount: 9,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/croc_chest.png",
    photoOverride: "sticker-croc",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
  },
  {
    id: "p45",
    slug: "sticker-blueprint-wolf",
    name: "Sticker Blueprint",
    band: "HOWL",
    tourYear: "",
    price: 5,
    rating: 4.7,
    reviewCount: 6,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/blueprint_wolf.png",
    photoOverride: "sticker-blueprint",
    logoStyle: { accentColor: "#3c4a5c" },
    tourDates: [],
  },
  {
    id: "p46",
    slug: "sticker-eternal",
    name: "Sticker Eternal",
    band: "永恆",
    tourYear: "",
    price: 5,
    rating: 4.8,
    reviewCount: 7,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/eternal_chest.png",
    photoOverride: "sticker-yinyang",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
  },
  {
    id: "p47",
    slug: "sticker-wolf-badge",
    name: "Sticker Wolf Badge",
    band: "HOWL",
    tourYear: "",
    price: 5,
    rating: 4.9,
    reviewCount: 3,
    description: "Sticker exclusivo — este diseño no existe en ninguna camiseta. Vinilo troquelado, resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño exclusivo, solo en sticker"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    photoOverride: "sticker-wolfbadge",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p48",
    slug: "sticker-rat-punk",
    name: "Sticker Rat Punk",
    band: "HOWL",
    tourYear: "",
    price: 5,
    rating: 4.9,
    reviewCount: 2,
    description: "Sticker exclusivo — este diseño no existe en ninguna camiseta. Vinilo troquelado, resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño exclusivo, solo en sticker"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    photoOverride: "sticker-rat",
    logoStyle: { accentColor: "#a8231c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p49",
    slug: "no-destination-wheel",
    name: "No Destination",
    band: "NO DESTINATION",
    backBand: "NO DESTINATION",
    tourYear: "",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.8,
    reviewCount: 4,
    description:
      "Camiseta de la colección Horizonte. Logo pequeño de rueda alada al pecho, motorista en la carretera grabado a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/no_destination_chest.png",
    backArtworkImage: "/artwork/no_destination_back.png",
    backHeroPhoto: "no_destination_back-black",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "RIDE TILL THE TANK RUNS DRY",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p50",
    slug: "loud-or-nothing",
    name: "Loud Or Nothing",
    band: "LOUD OR NOTHING",
    backBand: "LOUD OR NOTHING",
    tourYear: "",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.9,
    reviewCount: 3,
    description:
      "Camiseta de la colección Horizonte. Logo pequeño de púa alada al pecho, guitarra Les Paul grabada a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/loud_or_nothing_chest.png",
    backArtworkImage: "/artwork/loud_or_nothing_back.png",
    backHeroPhoto: "loud_or_nothing_back-black",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "UNDERGROUND SOUND",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p51",
    slug: "stampede-bison",
    name: "Stampede",
    band: "STAMPEDE",
    backBand: "STAMPEDE",
    tourYear: "",
    editionLabel: "Colección",
    price: 25.9,
    compareAtPrice: 32.9,
    rating: 4.8,
    reviewCount: 3,
    description:
      "Camiseta de la colección Horizonte. Logo pequeño de bisonte al pecho, manada corriendo al atardecer grabada a la espalda.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/stampede_chest.png",
    backArtworkImage: "/artwork/stampede_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "RUN WITH THE WILD ONES",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p53",
    slug: "la-trattoria-da-enzo",
    name: "La Trattoria",
    band: "DA ENZO",
    tourYear: "1974",
    editionLabel: "Colección",
    price: 27.9,
    compareAtPrice: 34.9,
    rating: 4.7,
    reviewCount: 3,
    description:
      "Camiseta de la colección Italiana. Sello vintage de trattoria desgastado al pecho — 'Ristorante Pizzeria Da Enzo, dal 1974'. Aire de menú de barrio italiano de los 80.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/trattoria_chest.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#8a2e2e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p54",
    slug: "crewneck-basics",
    name: "Crewneck Básica",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 49.9,
    compareAtPrice: 59.9,
    rating: 4.7,
    reviewCount: 2,
    description:
      "Sudadera crewneck de algodón grueso de alto gramaje, sin capucha, corte vintage. Wordmark HOWL pequeño al pecho — la básica de armario que no falla.",
    details: [
      "Algodón grueso 320 g/m², cuello redondo acanalado",
      "Puños y bajo acanalados, corte vintage oversize",
      "Wordmark HOWL serigrafiado al pecho",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/crewneck_chest.png",
    backHeroPhoto: "crewneck_back-black",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p55",
    slug: "dad-hat-h",
    name: "Dad Hat H",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 22.0,
    compareAtPrice: 27.0,
    rating: 4.6,
    reviewCount: 2,
    description:
      "Gorra dad hat de lona lavada, corte bajo sin estructurar, hebilla metálica trasera ajustable. Letra H bordada en relieve al frente.",
    details: [
      "Lona de algodón 100% lavada, tacto suave desde el primer uso",
      "Corte bajo sin estructurar, visera curva",
      "Hebilla metálica ajustable trasera, talla única",
      "Letra H bordada en relieve al frente",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/dadhat_front.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p56",
    slug: "crew-socks-howl",
    name: "Crew Socks",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 12.0,
    compareAtPrice: 15.0,
    rating: 4.7,
    reviewCount: 2,
    description:
      "Calcetines de caña alta, algodón grueso con canalé. Logotipo HOWL bordado en el lateral.",
    details: [
      "Algodón grueso con canalé, caña alta",
      "Logotipo HOWL bordado en el lateral",
      "Talla única, un par por pedido",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/socks_pair.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p57",
    slug: "answer-the-call-hoodie",
    name: "Answer The Call Hoodie",
    band: "HOWL",
    tourYear: "N.07",
    editionLabel: "Colección",
    price: 57.9,
    compareAtPrice: 69.9,
    rating: 4.8,
    reviewCount: 2,
    description:
      "Sudadera con capucha, algodón grueso de alto gramaje. El lobo y la luna de nuestra pieza insignia, ahora en formato sudadera.",
    details: [
      "Algodón/poliéster 340 g/m², interior perchado",
      "Capucha forrada, bolsillo canguro",
      "Corte oversize unisex",
      "Wolf + luna serigrafiado al pecho",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/hoodie_wolf_chest.png",
    backHeroPhoto: "hoodie-back-black",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#9aa0a6" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p58",
    slug: "tote-bag-howl",
    name: "Tote Bag",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 23.0,
    compareAtPrice: 28.0,
    rating: 4.8,
    reviewCount: 2,
    description:
      "Bolsa de algodón grueso resistente, wordmark HOWL minimalista al frente. Para el día a día — y para llegar al envío gratis.",
    details: [
      "Algodón grueso 100%, asas planas reforzadas",
      "Wordmark HOWL serigrafiado al frente",
      "Talla única",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/tote_bag.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p59",
    slug: "sticker-ufo",
    name: "Sticker UFO",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    rating: 4.8,
    reviewCount: 3,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_ship.png",
    photoOverride: "sticker-ufo",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p60",
    slug: "sticker-cow",
    name: "Sticker Cow",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    rating: 4.8,
    reviewCount: 2,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_cow.png",
    photoOverride: "sticker-cow",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
  },
];

export function getAllProducts(): Product[] {
  return products;
}

// Orden curado a mano por atractivo/potencial de venta, de más a menos.
const FEATURED_ORDER = [
  "answer-the-call-wolf",
  "swamp-crocodile",
  "wild-west-cowboy",
  "chase-the-horizon-mountains",
  "everglades-serpent",
  "rattlesnake-kings-scorched-earth",
  "nothing-like-home-cottage",
  "ufo-obsession",
];

/** Productos navegables en catálogo/inicio (excluye los ocultos por stock reducido temporal). */
export function getVisibleProducts(): Product[] {
  return products.filter((p) => p.visible !== false);
}

export function getNewProducts(limit = 8): Product[] {
  return getVisibleProducts()
    .filter((p) => p.isNew)
    .slice()
    .reverse()
    .slice(0, limit);
}

export function getFeaturedProducts(): Product[] {
  return FEATURED_ORDER.map((slug) => products.find((p) => p.slug === slug)).filter(
    (p): p is Product => Boolean(p && p.visible !== false)
  );
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return getVisibleProducts()
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function getCategories(): Product["category"][] {
  return Array.from(new Set(products.map((p) => p.category)));
}
