import type { Product, ProductColor } from "@/lib/types";

const inkBlack: ProductColor = { name: "Negro desteñido", hex: "#1c1712" };
const agedCream: ProductColor = { name: "Crema envejecida", hex: "#e7d9b8" };
const oxideRust: ProductColor = { name: "Óxido", hex: "#a8452a" };
const washedDenim: ProductColor = { name: "Azul lavado", hex: "#3c4a5c" };
const sunYellow: ProductColor = { name: "Amarillo cereza", hex: "#e0b23c" };
const offWhite: ProductColor = { name: "Albaricoque", hex: "#dba876" };

const tourTeeSizes: Product["sizes"] = ["S", "M", "L", "XL", "XXL"];

const standardDetails = [
  "Algodón peinado e hilado en anillos 237 g/m², corte boxy oversized",
  "Serigrafía envejecida con lavado ácido",
  "Corte unisex clásico de los 80/90",
  "Corte oversized — pide una talla menos si lo prefieres ajustado",
  "Tirada limitada — no se reimprime",
];

const lifestyleDetails = [
  "Algodón peinado e hilado en anillos 237 g/m², corte boxy oversized",
  "Estampado digital de alta resolución",
  "Corte unisex regular",
  "Corte oversized — pide una talla menos si lo prefieres ajustado",
  "Edición limitada numerada",
];

export const products: Product[] = [
  {
    id: "p2",
    slug: "everglades-serpent",
    name: "Everglades",
    band: "EVERGLADES",
    tourYear: "N.10",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Una serpiente enroscada al pecho, para quien prefiere el pantano a la ciudad — donde mandan las bestias y no el asfalto.",
      descriptionEn:
      "A coiled serpent on the chest, for anyone who prefers the swamp to the city — where the beasts and nature live, not the pavement.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, agedCream],
    graphic: "serpent",
    artworkImage: "/artwork/serpent.png",
    tagline: "WHERE THE BEASTS AND NATURE LIVE",
    logoStyle: { skew: -6, accentColor: "#8fd13b" },
    tourDates: [],
    backHeroPhotoByColor: {
      "#1c1712": "everglades-back-black",
      "#a8452a": "everglades-back-rust",
      "#e7d9b8": "everglades-back-cream",
    },
  },
  {
    id: "p4",
    slug: "coyote-wire-static",
    name: "Static",
    band: "STATIC",
    tourYear: "",
    price: 39.95,
    description:
      "Un rayo estampado a mano, colorido apagado por el sol — como si llevara años colgado en el mismo armario.",
      descriptionEn:
      "A hand-printed lightning bolt, colors faded by the sun — like it's hung in the same closet for years.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "bolt",
    artworkImage: "/artwork/bolt.png",
    tagline: "STRUCK NOT STIRRED",
    logoStyle: { skew: 8, accentColor: "#33c6f4" },
    tourDates: [],
  },
  {
    id: "p5",
    slug: "hollow-saints-midnight-mass",
    visible: false,
    name: "Midnight Mass",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Wordmark discreto al pecho; la luna duerme con gorro y manta a la espalda — para quien también se queda despierto pensando en nada a las tres de la mañana.",
      descriptionEn:
      "Discreet wordmark on the chest; the moon sleeps with a nightcap and blanket on the back — for anyone else who lies awake thinking about nothing at 3am.",
    details: standardDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "moon",
    artworkImage: "/artwork/moon.png",
    frontLogoOnly: true,
    backHeroPhotoByColor: {
      "#1c1712": "moon-back-black",
    },
    tagline: "STILL AWAKE. STILL NORMAL.",
    logoStyle: { accentColor: "#7ec8e3" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p6",
    slug: "iron-magnolia-southbound",
    name: "Southbound",
    band: "SOUTHBOUND",
    tourYear: "",
    price: 39.95,
    description:
      "Alas oxidadas y letras resquebrajadas, con el aire de un clásico de mercadillo de discos que nadie recuerda de dónde salió.",
      descriptionEn:
      "Rusted wings and cracked lettering, with the feel of a record-crate classic nobody remembers where it came from.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "wings",
    artworkImage: "/artwork/wings.png",
    tagline: "RUST NEVER DIES",
    logoStyle: { skew: -3, accentColor: "#d9662b" },
    tourDates: [],
  },
  {
    id: "p7",
    slug: "midnight-combine-harvest-of-noise",
    visible: false,
    name: "Harvest Of Noise",
    band: "HARVEST OF NOISE",
    tourYear: "",
    price: 60,
    description:
      "Sudadera con capucha de algodón pesado. Llama pequeña al pecho con el HOWL escondido dentro — interior perchado, sin nada a la espalda.",
      descriptionEn:
      "Heavyweight cotton hoodie. Small flame on the chest with HOWL hidden inside — brushed interior, nothing on the back.",
    details: [
      "Algodón/poliéster 320 g/m², interior perchado",
      "Serigrafía envejecida con lavado ácido",
      "Corte oversize unisex",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "flame",
    artworkImage: "/artwork/flame.png",
    backHeroPhotoByColor: {
      "#1c1712": "hoodie-back-black",
      "#e7d9b8": "hoodie-back-cream",
    },
    frontLogoOnly: true,
    logoStyle: { skew: -4, accentColor: "#e8452c" },
    tourDates: [],
  },
  {
    id: "p10",
    slug: "rattlesnake-kings-scorched-earth",
    name: "Scorched Earth",
    band: "SCORCHED EARTH",
    tourYear: "",
    price: 39.95,
    description:
      "Un escorpión al acecho, estampado en tinta única — para las noches más calurosas del desierto.",
      descriptionEn:
      "A lurking scorpion, printed in a single ink — for the hottest desert nights.",
    details: standardDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, agedCream],
    graphic: "scorpion",
    artworkImage: "/artwork/scorpion.png",
    tagline: "STING FIRST, ASK LATER",
    logoStyle: { skew: 4, accentColor: "#c9d92b" },
    tourDates: [],
    isNew: true,
    backHeroPhotoByColor: {
      "#a8452a": "rattlesnake-back-rust",
      "#1c1712": "rattlesnake-back-black",
      "#e7d9b8": "rattlesnake-back-cream",
    },
  },
  {
    id: "p11",
    slug: "imagine-the-world-clouds",
    name: "Imagine The World",
    band: "IMAGINE THE WORLD",
    tourYear: "N.01",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Un cielo real, colinas verdes y una frase que dice todo lo que hace falta decir. Icono plano, una sola tinta, pensado para leerse limpio a cualquier tamaño.",
      descriptionEn:
      "A real sky, green hills, and a line that says all it needs to. Flat icon, single ink, built to read clean at any size.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/clouds.png",
    tagline: "ONE SKY, ONE EARTH",
    logoStyle: { accentColor: "#4fa8d8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p12",
    slug: "nothing-like-home-cottage",
    name: "Nothing Like Home",
    band: "NOTHING LIKE HOME",
    tourYear: "N.02",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Una casita de campo inglesa, jardín florido y ganas de quedarse en casa un domingo entero. Para los días en que ningún sitio le gana al sofá.",
      descriptionEn:
      "An English cottage, a garden in bloom, and the urge to just stay home all Sunday. For the days nowhere beats the couch.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, oxideRust, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/cottage.png",
    tagline: "EAST, WEST, HOME'S BEST",
    logoStyle: { accentColor: "#c98a3e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p13",
    slug: "chase-the-horizon-mountains",
    visible: false,
    name: "Chase The Horizon",
    band: "CHASE THE HORIZON",
    tourYear: "N.03",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Una cordillera al atardecer para quien nunca deja de mirar más allá de donde está. Algodón grueso, lavado suave, colores que ya vienen desgastados de fábrica.",
      descriptionEn:
      "A mountain range at sunset for anyone who never stops looking past where they are. Heavyweight cotton, soft wash, colors that come pre-worn from the start.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [oxideRust, inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/mountains.png",
    tagline: "NEVER STOP EXPLORING",
    logoStyle: { accentColor: "#e8752c" },
    tourDates: [],
    isNew: true,
    backHeroPhotoByColor: {
      "#a8452a": "chase-back-rust",
      "#1c1712": "chase-back-black",
      "#3c4a5c": "chase-back-denim",
    },
  },
  {
    id: "p14",
    slug: "slow-down-breathe-beach",
    name: "Slow Down, Breathe",
    band: "SLOW DOWN, BREATHE",
    tourYear: "N.04",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Palmeras, atardecer y el recordatorio de que no pasa nada por ir más despacio de vez en cuando. Corte oversized, la paleta lavada de siempre.",
      descriptionEn:
      "Palm trees, sunset, and the reminder that it's fine to slow down every now and then. Oversized cut, our usual washed-out palette.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/beach.png",
    tagline: "PARADISE FOUND",
    logoStyle: { accentColor: "#f2a03d" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p15",
    slug: "made-for-the-night-skyline",
    name: "Made For The Night",
    band: "MADE FOR THE NIGHT",
    tourYear: "N.05",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Rascacielos, reflejos en el agua y esa energía que solo tiene la ciudad de noche. Para cuando el día se acaba y el plan recién empieza.",
      descriptionEn:
      "Skyscrapers, reflections on the water, and that energy only a city at night has. For when the day ends and the plan is just getting started.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/skyline.png",
    tagline: "CITY LIGHTS, CLEAR MIND",
    logoStyle: { accentColor: "#6fa8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p16",
    slug: "take-the-long-way-roadtrip",
    name: "Take The Long Way",
    band: "TAKE THE LONG WAY",
    tourYear: "N.06",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Una furgoneta, una carretera del desierto y ninguna prisa por llegar a ningún sitio. El camino largo, a propósito.",
      descriptionEn:
      "A van, a desert road, and no rush to get anywhere. The long way, on purpose.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/roadtrip.png",
    tagline: "DESERT HIGHWAY DREAMS",
    logoStyle: { accentColor: "#d9793f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p17",
    slug: "answer-the-call-wolf",
    name: "Answer The Call",
    band: "HOWL",
    tourYear: "N.07",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "La escena que le da nombre a HOWL: un lobo aullando a la luna, montañas detrás. Icono pequeño al pecho, ilustración completa a la espalda — el formato que repetimos en buena parte del catálogo. Algodón grueso 237 g/m², serigrafía con lavado ácido, como si llevara diez años en el armario de alguien. Cuando se agote, no vuelve.",
      descriptionEn:
      "The scene that gives HOWL its name: a wolf howling at the moon, mountains behind it. Small icon on the chest, full illustration on the back — the format we repeat across much of the catalog. Heavyweight 237 g/m² cotton, acid-washed print, like it's already spent ten years in someone's closet. Once it's gone, it's gone.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/wolfmoon.png",
    frontLogoOnly: true,
    tagline: "ANSWER THE CALL",
    logoStyle: { accentColor: "#9aa0a6" },
    tourDates: [],
    isNew: true,
    backHeroPhoto: "wolfmoon-back-black",
  },
  {
    id: "p18",
    slug: "swamp-crocodile",
    visible: false,
    name: "Swamp",
    band: "SWAMP",
    tourYear: "",
    price: 39.95,
    description:
      "Un cocodrilo asomando junto al muelle, un pescador que no se entera de nada — la escena completa a la espalda, solo el cocodrilo al pecho. La paciencia siempre gana.",
      descriptionEn:
      "A crocodile surfacing by the dock, a fisherman who has no idea — the full scene on the back, just the crocodile on the chest. Patience always wins.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/croc_chest.png",
    backArtworkImage: "/artwork/croc_lake.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "PATIENCE PAYS OFF",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p19",
    slug: "wild-west-cowboy",
    name: "Wild West",
    band: "WILD WEST",
    tourYear: "N.09",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Un jinete pequeño al pecho. A la espalda, la escena completa: \"Hard Times Build Hard Men\". Es la pieza más pesada del catálogo — estampado delante y detrás, 237 g/m² de algodón boxy oversized. Para quien prefiere el polvo del camino a la acera.",
      descriptionEn:
      "A small rider on the chest. On the back, the full scene: \"Hard Times Build Hard Men.\" The heaviest piece in the catalog — printed front and back, 237 g/m² boxy oversized cotton. For anyone who'd rather have dust on their boots than pavement.",
    details: [
      "Algodón peinado e hilado en anillos 237 g/m², corte boxy oversized",
      "Estampado delante y detrás — la pieza más pesada de la colección",
      "Corte unisex regular",
      "Corte oversized — pide una talla menos si lo prefieres ajustado",
      "Edición limitada numerada",
    ],
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/print-ready/wild-west-cowboy-front-crest.png",
    backArtworkImage: "/artwork/cowboy.png",
    backTextBaked: true,
    frontLogoOnly: true,
    logoStyle: { accentColor: "#4a7ab8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p20",
    slug: "ufo-obsession",
    visible: false,
    name: "UFO Obsession",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 39.95,
    description:
      "Un platillo discreto al pecho, la abducción de una vaca de campo grabada a la espalda — para quien cree que no estamos solos.",
      descriptionEn:
      "A discreet saucer on the chest, a cow's abduction from a field engraved on the back — for anyone who believes we're not alone.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_chest_ship.png",
    backArtworkImage: "/artwork/ufo_scene.png",
    frontLogoOnly: true,
    tagline: "WE ARE NOT ALONE",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
    backHeroPhotoByColor: {
      "#1c1712": "ufo_scene-black",
      "#e7d9b8": "ufo_scene-cream",
    },
  },
  {
    id: "p21",
    slug: "tradition-innovation-crane",
    visible: false,
    name: "Tradition & Innovation",
    band: "伝統と革新",
    tourYear: "",
    price: 39.95,
    description:
      "Sol naciente, montañas y una gran ola en tinta tradicional japonesa sobre algodón grueso. Lo antiguo y lo nuevo en la misma tela.",
      descriptionEn:
      "Rising sun, mountains and a great wave in traditional Japanese ink on heavyweight cotton. The old and the new on the same cloth.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/japan_wave.png",
    tagline: "TRADITION MEETS INNOVATION",
    logoStyle: { accentColor: "#c9463e" },
    tourDates: [],
    isNew: true,
    backHeroPhotoByColor: {
      "#e7d9b8": "tradition-back-cream",
      "#1c1712": "tradition-back-black",
    },
  },
  {
    id: "p22",
    slug: "camel-desert",
    name: "Camel",
    band: "CAMEL",
    tourYear: "N.11",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Un camello ornamentado, quieto frente a la puesta de sol del desierto. No tiene prisa y no la va a tener.",
      descriptionEn:
      "An ornamented camel, still against the desert sunset. It's not in a hurry and never will be.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/camel.png",
    tagline: "RELENTLESS IN THE DESERT",
    logoStyle: { accentColor: "#d9a441" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p23",
    slug: "howl-project-basics",
    visible: false,
    name: "Howl Project",
    band: "HOWL",
    backBand: "HOWL PROJECT",
    tourYear: "N.12",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Solo tipografía, sin ilustración — para los días de \"menos es más\". La básica de armario que no falla, en cuatro colores.",
      descriptionEn:
      "Typography only, no illustration — for the \"less is more\" days. The wardrobe basic that never fails, in four colors.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim, offWhite],
    graphic: "landscape",
    artworkImage: "/artwork/howl-wordmark.png",
    frontLogoOnly: true,
    textOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
    backHeroPhotoByColor: {
      "#1c1712": "howl-project-back-black",
      "#e7d9b8": "howl-project-back-cream",
      "#3c4a5c": "howl-project-back-denim",
    },
  },
  {
    id: "p24",
    slug: "everything-is-fine",
    name: "Everything Is Fine",
    band: "EVERYTHING IS FINE",
    tourYear: "N.13",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Una llama, un icono, y la calma de saber que todo va bien aunque no lo parezca. Diseño mínimo, una sola tinta.",
      descriptionEn:
      "A flame, an icon, and the calm of knowing everything's fine even when it doesn't look like it. Minimal design, single ink.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/flame_icon.png",
    logoStyle: { accentColor: "#e8752c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p25",
    slug: "raised-by-dragons",
    visible: false,
    name: "Raised By Dragons",
    band: "RAISED BY DRAGONS",
    tourYear: "2024",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Dragón pequeño al pecho, ilustración grande a la espalda — año del dragón, si te va la numerología. Si no, es solo un dragón que impone.",
      descriptionEn:
      "Small dragon on the chest, big illustration on the back — year of the dragon, if you're into that. If not, it's just a dragon that commands the room.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/dragon_chest.png",
    backArtworkImage: "/artwork/dragon_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "YEAR OF THE DRAGON",
    logoStyle: { accentColor: "#c9463e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p26",
    slug: "sunday-afternoon-route-66",
    visible: false,
    name: "Sunday Afternoon",
    band: "SUNDAY AFTERNOON",
    backBand: "SUNDAY AFTERNOON",
    tourYear: "2024",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Logo pequeño al pecho, una gasolinera de Route 66 ilustrada a toda espalda — llenar el depósito para la semana, en sentido literal y figurado.",
      descriptionEn:
      "Small logo on the chest, an illustrated Route 66 gas station across the whole back — filling the tank for the week, literally and otherwise.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/sunday_chest.png",
    backArtworkImage: "/artwork/sunday_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "FILL THE TANK FOR THE WEEK",
    logoStyle: { accentColor: "#4a7a9c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p27",
    slug: "nightfall-dive-hawk",
    name: "Nightfall Dive",
    band: "NIGHTFALL DIVE",
    tourYear: "",
    price: 39.95,
    description:
      "Un halcón en picado, línea fina, una sola tinta. Sin ruido de más — el diseño hace todo el trabajo.",
      descriptionEn:
      "A diving hawk, fine line, one ink. No extra noise — the design does all the work.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "wings",
    artworkImage: "/artwork/nightfall_dive.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p28",
    slug: "moth-flame",
    name: "Moth & Flame",
    band: "MOTH & FLAME",
    tourYear: "",
    price: 39.95,
    description:
      "Una polilla nocturna descendiendo hacia la llama. Línea fina, una tinta, la clase de diseño que se lee mejor cuanto más pequeño es.",
      descriptionEn:
      "A night moth descending toward the flame. Fine line, single ink, the kind of design that reads better the smaller it gets.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "moon",
    artworkImage: "/artwork/moth_flame.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p29",
    slug: "lost-bearing-compass",
    name: "Lost Bearing",
    band: "LOST BEARING",
    tourYear: "",
    price: 39.95,
    description:
      "Una brújula vieja, mellada, aguja torcida — no siempre hace falta saber a dónde vas. Línea fina, una tinta.",
      descriptionEn:
      "An old, nicked compass with a crooked needle — you don't always need to know where you're going. Fine line, single ink.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "star",
    artworkImage: "/artwork/lost_bearing.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p30",
    slug: "cut-loose-anchor",
    name: "Cut Loose",
    band: "CUT LOOSE",
    tourYear: "",
    price: 39.95,
    description:
      "Un ancla y una cuerda deshilachada — desanclarse, cortar por lo sano. Línea fina, una tinta.",
      descriptionEn:
      "An anchor and a frayed rope — cutting loose, clean and simple. Fine line, single ink.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "cross",
    artworkImage: "/artwork/cut_loose.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p31",
    slug: "old-iron-helmet",
    name: "Old Iron",
    band: "OLD IRON",
    tourYear: "",
    price: 39.95,
    description:
      "Casco motero vintage con gafas de aviador, línea fina, una tinta. El tipo de diseño que parece llevar más años en la carretera que tú.",
      descriptionEn:
      "Vintage biker helmet with aviator goggles, fine line, single ink. The kind of design that looks like it's spent more years on the road than you have.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, oxideRust, agedCream],
    graphic: "skull",
    artworkImage: "/artwork/old_iron.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p32",
    slug: "unbroken-knot",
    name: "Unbroken",
    band: "UNBROKEN",
    tourYear: "",
    price: 39.95,
    description:
      "Nudo marinero en figura de ocho — vínculo, lealtad, lo que no se suelta. Línea fina, una tinta.",
      descriptionEn:
      "A figure-eight sailor's knot — bond, loyalty, the kind that doesn't come undone. Fine line, single ink.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, washedDenim],
    graphic: "cross",
    artworkImage: "/artwork/unbroken.png",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p34",
    slug: "howl-vintage-wolf",
    name: "Vintage Howl",
    band: "HOWL",
    tourYear: "",
    price: 39.95,
    description:
      "El lobo de siempre, pero en grabado vintage y tipografía stencil — como si el diseño llevara ahí desde antes de que existiera la marca.",
      descriptionEn:
      "Our usual wolf, but in vintage engraving and stencil type — like the design was already there before the brand existed.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, washedDenim],
    graphic: "moon",
    artworkImage: "/artwork/howl_wolf_vintage.png",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p35",
    slug: "stay-feral",
    name: "Stay Feral",
    band: "STAY FERAL",
    tourYear: "",
    price: 39.95,
    description:
      "Tipografía brutalista, collage punk/fanzine — fotocopiada, recortada, pegada a mano. Nada demasiado limpio a propósito.",
      descriptionEn:
      "Brutalist type, punk/fanzine collage — photocopied, cut up, pasted by hand. Nothing too clean on purpose.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [agedCream, oxideRust],
    graphic: "bolt",
    artworkImage: "/artwork/stay_feral.png",
    textOnly: false,
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p36",
    slug: "love-is-a-long-road",
    name: "Love Is A Long Road",
    band: "LOVE IS A LONG ROAD",
    tourYear: "",
    price: 39.95,
    description:
      "Un muscle car de los 70 al atardecer, script retro dibujado a mano. El amor como carretera larga, no como atajo.",
      descriptionEn:
      "A 70s muscle car at sunset, hand-drawn retro script. Love as the long road, not the shortcut.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream, oxideRust],
    graphic: "landscape",
    artworkImage: "/artwork/love_long_road_v2.png",
    logoStyle: { accentColor: "#d9793f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p37",
    slug: "blueprint-wolf",
    name: "Blueprint",
    band: "HOWL",
    tourYear: "N.01",
    editionLabel: "Especimen",
    price: 39.95,
    description:
      "Cráneo de lobo despiezado en plano técnico, con el aire de una patente antigua — como si HOWL tuviera manual de instrucciones.",
      descriptionEn:
      "A wolf skull broken down like a technical blueprint, with the look of an old patent drawing — as if HOWL came with an instruction manual.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, washedDenim, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/blueprint_wolf.png",
    logoStyle: { accentColor: "#3c4a5c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p38",
    slug: "freedom-nyc",
    visible: false,
    name: "Freedom",
    band: "NYC",
    backBand: "FREEDOM",
    tourYear: "",
    price: 39.95,
    description:
      "Logo pequeño NYC al pecho, la Estatua de la Libertad grabada en toda la espalda — el recuerdo de ciudad que nunca compraste en una tienda de souvenirs.",
      descriptionEn:
      "Small NYC logo on the chest, the Statue of Liberty engraved across the back — the city souvenir you never actually bought in a gift shop.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/nyc_chest.png",
    backArtworkImage: "/artwork/freedom_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p39",
    slug: "cherry-howl-supply-co",
    name: "Cherry Supply Co.",
    band: "HOWL SUPPLY CO.",
    tourYear: "MMXXIV",
    price: 39.95,
    description:
      "Camiseta amarilla, cerezas vintage y wordmark universitario en el pecho — la pieza más dulce del catálogo, sin pedir perdón por serlo.",
      descriptionEn:
      "Yellow tee, vintage cherries and a collegiate wordmark on the chest — the sweetest piece in the catalog, no apologies.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [sunYellow],
    graphic: "landscape",
    artworkImage: "/artwork/cherry_howl.png",
    logoStyle: { accentColor: "#a8231c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p40",
    slug: "howlers",
    visible: false,
    name: "Howlers",
    band: "HOWLERS",
    backBand: "HOWLERS",
    tourYear: "2026",
    editionLabel: "Especial",
    price: 39.95,
    description:
      "Camiseta especial HOWL. Lobo en línea fina al pecho, la manada aullando junta en la espalda.",
      descriptionEn:
      "Special HOWL tee. Fine-line wolf on the chest, the whole pack howling together on the back.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/howlers.png",
    backArtworkImage: "/artwork/howlers_pack.png",
    backTextBaked: true,
    logoStyle: { accentColor: "#1c1712" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p41",
    slug: "eternal-yinyang",
    name: "Eternal",
    band: "永恆",
    backBand: "永恆",
    tourYear: "",
    price: 39.95,
    description:
      "Yin-yang pequeño al pecho; a la espalda, grande y acompañado de caligrafía china — el equilibrio como diseño, no solo como frase.",
      descriptionEn:
      "Small yin-yang on the chest; on the back, large and paired with Chinese calligraphy — balance as a design, not just a saying.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [washedDenim, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/eternal_chest.png",
    backArtworkImage: "/artwork/eternal_back.png",
    frontLogoOnly: true,
    backHeroPhotoByColor: {
      "#3c4a5c": "eternal_back-denim",
      "#1c1712": "eternal_back-black",
    },
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p42",
    slug: "lunar-hotel",
    visible: false,
    name: "Lunar Hotel",
    band: "HOWL",
    backBand: "LUNAR HOTEL",
    tourYear: "2047",
    price: 39.95,
    description:
      "Luna pequeña al pecho, un hotel lunar retro-futurista grabado a la espalda — ciencia ficción de portada de libro de bolsillo de los 70.",
      descriptionEn:
      "Small moon on the chest, a retro-futuristic lunar hotel engraved on the back — 70s pulp-paperback science fiction energy.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [washedDenim],
    graphic: "landscape",
    artworkImage: "/artwork/lunar_chest.png",
    backArtworkImage: "/artwork/lunar_back.png",
    frontLogoOnly: true,
    backHeroPhoto: "lunar_back-denim",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p43",
    slug: "sticker-alien",
    visible: false,
    name: "Sticker Alien",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_chest.png",
    photoOverride: "sticker-alien",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
  },
  {
    id: "p44",
    slug: "sticker-crocodile",
    visible: false,
    name: "Sticker Crocodile",
    band: "SWAMP",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/croc_chest.png",
    photoOverride: "sticker-croc",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
  },
  {
    id: "p45",
    slug: "sticker-blueprint-wolf",
    visible: false,
    name: "Sticker Blueprint",
    band: "HOWL",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/blueprint_wolf.png",
    photoOverride: "sticker-blueprint",
    logoStyle: { accentColor: "#3c4a5c" },
    tourDates: [],
  },
  {
    id: "p46",
    slug: "sticker-eternal",
    visible: false,
    name: "Sticker Eternal",
    band: "永恆",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/eternal_chest.png",
    photoOverride: "sticker-yinyang",
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
  },
  {
    id: "p47",
    slug: "sticker-wolf-badge",
    visible: false,
    name: "Sticker Wolf Badge",
    band: "HOWL",
    tourYear: "",
    price: 5,
    description: "Sticker exclusivo — este diseño no existe en ninguna camiseta. Vinilo troquelado, resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Exclusive sticker — this design doesn't exist on any tee. Die-cut vinyl, water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño exclusivo, solo en sticker"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    photoOverride: "sticker-wolfbadge",
    logoStyle: { accentColor: "#7a9a3f" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p48",
    slug: "sticker-rat-punk",
    visible: false,
    name: "Sticker Rat Punk",
    band: "HOWL",
    tourYear: "",
    price: 5,
    description: "Sticker exclusivo — este diseño no existe en ninguna camiseta. Vinilo troquelado, resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Exclusive sticker — this design doesn't exist on any tee. Die-cut vinyl, water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño exclusivo, solo en sticker"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    photoOverride: "sticker-rat",
    logoStyle: { accentColor: "#a8231c" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p49",
    slug: "no-destination-wheel",
    name: "No Destination",
    band: "NO DESTINATION",
    backBand: "NO DESTINATION",
    tourYear: "",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Logo pequeño de rueda alada al pecho, un motorista en la carretera grabado a toda espalda — sin destino fijo, con el depósito lleno.",
      descriptionEn:
      "Small winged-wheel logo on the chest, a biker on the road engraved across the back — no fixed destination, full tank.",
    details: lifestyleDetails,
    category: "Camisetas",
    visible: false,
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/no_destination_chest.png",
    backArtworkImage: "/artwork/no_destination_back.png",
    backHeroPhoto: "no_destination_back-black",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "RIDE TILL THE TANK RUNS DRY",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p50",
    slug: "loud-or-nothing",
    visible: false,
    name: "Loud Or Nothing",
    band: "LOUD OR NOTHING",
    backBand: "LOUD OR NOTHING",
    tourYear: "",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Logo pequeño de púa alada al pecho, una Les Paul grabada a toda espalda — para quien piensa que si no suena fuerte, no cuenta.",
      descriptionEn:
      "Small winged-pick logo on the chest, a Les Paul engraved across the back — for anyone who thinks if it's not loud, it doesn't count.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/loud_or_nothing_chest.png",
    backArtworkImage: "/artwork/loud_or_nothing_back.png",
    backHeroPhoto: "loud_or_nothing_back-black",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "UNDERGROUND SOUND",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p51",
    slug: "stampede-bison",
    name: "Stampede",
    band: "STAMPEDE",
    backBand: "STAMPEDE",
    tourYear: "",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Un bisonte pequeño al pecho. Detrás, la manada entera corriendo hacia el atardecer, grabada en toda la espalda. Algodón grueso 237 g/m², serigrafía envejecida — el peso y el lavado que buscamos en cada pieza del catálogo. Corre con los que no se paran.",
      descriptionEn:
      "A small bison on the chest. On the back, the whole herd running toward sunset, engraved across the full back panel. Heavyweight 237 g/m² cotton, aged screen print — the weight and wash we chase in every piece we make. Run with the ones who don't stop.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/stampede_chest.png",
    backArtworkImage: "/artwork/stampede_back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "RUN WITH THE WILD ONES",
    logoStyle: { accentColor: "#c0392b" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p53",
    slug: "la-trattoria-da-enzo",
    visible: false,
    name: "La Trattoria",
    band: "DA ENZO",
    tourYear: "1974",
    editionLabel: "Colección",
    price: 39.95,
    description:
      "Sello vintage de trattoria desgastado al pecho — 'Ristorante Pizzeria Da Enzo, dal 1974'. Aire de menú de barrio italiano de los 80, del tipo que no cambia nunca.",
      descriptionEn:
      "A worn vintage trattoria seal on the chest — 'Ristorante Pizzeria Da Enzo, dal 1974.' The feel of an 80s neighborhood Italian menu, the kind that never changes.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [agedCream, inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/trattoria_chest.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#8a2e2e" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p54",
    slug: "crewneck-basics",
    visible: false,
    name: "Crewneck Básica",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 60,
    description:
      "Sudadera crewneck de algodón grueso de alto gramaje, sin capucha, corte vintage. Wordmark HOWL pequeño al pecho — la básica de armario que no falla.",
      descriptionEn:
      "Heavyweight cotton crewneck, no hood, vintage cut. Small HOWL wordmark on the chest — the wardrobe basic that never fails.",
    details: [
      "Algodón grueso 320 g/m², cuello redondo acanalado",
      "Puños y bajo acanalados, corte vintage oversize",
      "Wordmark HOWL serigrafiado al pecho",
      "Tirada limitada — no se reimprime",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/crewneck_chest.png",
    backHeroPhotoByColor: {
      "#1c1712": "crewneck_back-black",
      "#e7d9b8": "crewneck_back-cream",
    },
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p55",
    slug: "dad-hat-h",
    visible: false,
    name: "Dad Hat H",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 22.0,
    description:
      "Gorra dad hat de lona lavada, corte bajo sin estructurar, hebilla metálica trasera ajustable. Letra H bordada en relieve al frente.",
      descriptionEn:
      "Washed canvas dad hat, unstructured low crown, adjustable metal back buckle. Embroidered raised H on the front.",
    details: [
      "Lona de algodón 100% lavada, tacto suave desde el primer uso",
      "Corte bajo sin estructurar, visera curva",
      "Hebilla metálica ajustable trasera, talla única",
      "Letra H bordada en relieve al frente",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/dadhat_front.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p56",
    slug: "crew-socks-howl",
    visible: false,
    name: "Crew Socks",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 12.0,
    description:
      "Calcetines de caña alta, algodón grueso con canalé. Logotipo HOWL bordado en el lateral.",
      descriptionEn:
      "Crew-length socks, thick ribbed cotton. HOWL logo embroidered on the side.",
    details: [
      "Algodón grueso con canalé, caña alta",
      "Logotipo HOWL bordado en el lateral",
      "Talla única, un par por pedido",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/socks_pair.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p57",
    slug: "answer-the-call-hoodie",
    name: "Answer The Call Hoodie",
    band: "HOWL",
    tourYear: "N.07",
    editionLabel: "Colección",
    price: 60,
    description:
      "El lobo y la luna de nuestra pieza insignia, ahora en sudadera. Algodón/poliéster de 340 g/m², interior perchado, capucha forrada y bolsillo canguro — para cuando el frío no perdona. Wolf serigrafiado al pecho, corte oversize sin complicarse la vida.",
      descriptionEn:
      "The wolf and the moon from our flagship tee, now in hoodie form. 340 g/m² cotton/poly, brushed interior, lined hood and kangaroo pocket — for when the cold doesn't care. Wolf screen-printed on the chest, oversize cut, nothing complicated about it.",
    details: [
      "Algodón/poliéster 340 g/m², interior perchado",
      "Capucha forrada, bolsillo canguro",
      "Corte oversize unisex",
      "Wolf + luna serigrafiado al pecho",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/hoodie_wolf_chest.png",
    backHeroPhotoByColor: {
      "#1c1712": "hoodie-back-black",
      "#e7d9b8": "hoodie-back-cream",
    },
    frontLogoOnly: true,
    logoStyle: { accentColor: "#9aa0a6" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p61",
    slug: "howl-hoodie-logo",
    name: "Howl Hoodie",
    band: "HOWL",
    tourYear: "N.13",
    editionLabel: "Colección",
    price: 60,
    description:
      "Solo el wordmark HOWL al pecho — para los días de 'menos es más'. Mismo algodón/poliéster de 340 g/m² y capucha forrada que el resto de sudaderas, sin ningún dibujo que explicar.",
    descriptionEn:
      "Just the HOWL wordmark on the chest — for the 'less is more' days. Same 340 g/m² cotton/poly and lined hood as the rest of the hoodie line, no illustration to explain.",
    details: [
      "Algodón/poliéster 340 g/m², interior perchado",
      "Capucha forrada, bolsillo canguro",
      "Corte oversize unisex",
      "Wordmark HOWL serigrafiado al pecho",
    ],
    category: "Sudaderas",
    sizes: tourTeeSizes,
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/howl-hoodie-logo.png",
    frontLogoOnly: true,
    textOnly: true,
    backHeroPhotoByColor: {
      "#1c1712": "hoodie-back-black",
      "#e7d9b8": "hoodie-back-cream",
    },
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p58",
    slug: "tote-bag-howl",
    visible: false,
    name: "Tote Bag",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 23.0,
    description:
      "Bolsa de algodón grueso resistente, wordmark HOWL minimalista al frente. Para el día a día — y para llegar al envío gratis.",
      descriptionEn:
      "Sturdy heavyweight cotton tote, minimalist HOWL wordmark on the front. For every day — and for hitting free shipping.",
    details: [
      "Algodón grueso 100%, asas planas reforzadas",
      "Wordmark HOWL serigrafiado al frente",
      "Talla única",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack, agedCream],
    graphic: "landscape",
    artworkImage: "/artwork/tote_bag.png",
    frontLogoOnly: true,
    logoStyle: { accentColor: "#efe4c8" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p59",
    slug: "sticker-ufo",
    visible: false,
    name: "Sticker UFO",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_ship.png",
    photoOverride: "sticker-ufo",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p60",
    slug: "sticker-cow",
    visible: false,
    name: "Sticker Cow",
    band: "UFO OBSESSION",
    tourYear: "",
    price: 5,
    description: "Sticker vinilo troquelado. Resistente al agua y a los rayos UV. 8cm aprox.",
    descriptionEn: "Die-cut vinyl sticker. Water and UV resistant. ~8cm.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "8cm aprox.", "Diseño ya presente en camiseta"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/ufo_cow.png",
    photoOverride: "sticker-cow",
    logoStyle: { accentColor: "#8fb8c9" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p62",
    slug: "sticker-howl-wordmark",
    name: "Sticker HOWL",
    band: "HOWL",
    tourYear: "",
    price: 2.5,
    description: "El wordmark HOWL tal cual, sin icono ni escena — troquelado en vinilo de 5cm, aguanta agua y sol sin decolorarse.",
    descriptionEn: "The HOWL wordmark on its own, no icon or scene — 5cm die-cut vinyl, holds up to water and sun without fading.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "5cm", "Incluido gratis con cada pedido"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/stickers/sticker_howl_wordmark.png",
    photoOverride: "sticker-howl-wordmark-gift",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p63",
    slug: "sticker-wild-west",
    name: "Sticker Wild West",
    band: "WILD WEST",
    tourYear: "",
    price: 2.5,
    description: "El jinete de \"Hard Times Build Hard Men\" en miniatura — vinilo troquelado de 5cm, resiste agua y sol sin despegarse.",
    descriptionEn: "The \"Hard Times Build Hard Men\" rider in miniature — 5cm die-cut vinyl, weatherproof and won't peel.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "5cm", "Incluido gratis con cada pedido"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/stickers/sticker_wild_west.png",
    photoOverride: "sticker-wild-west-gift",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p64",
    slug: "sticker-stampede",
    name: "Sticker Stampede",
    band: "STAMPEDE",
    tourYear: "",
    price: 2.5,
    description: "Cabeza de bisonte en insignia circular, inspirada en Stampede, en formato sticker de 5cm — vinilo resistente al agua y al sol.",
    descriptionEn: "A bison head in a circular badge, inspired by Stampede, as a 5cm sticker — water and UV resistant vinyl.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "5cm", "Incluido gratis con cada pedido"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/stickers/sticker_stampede.png",
    photoOverride: "sticker-stampede-gift",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p65",
    slug: "sticker-wolfmoon",
    name: "Sticker Answer The Call",
    band: "HOWL",
    tourYear: "",
    price: 2.5,
    description: "El lobo aullando a la luna que da nombre a la marca, en vinilo troquelado de 5cm — aguanta agua y sol sin decolorarse.",
    descriptionEn: "The howling wolf that gives the brand its name, as a 5cm die-cut vinyl sticker — holds up to water and sun without fading.",
    details: ["Vinilo troquelado resistente al agua", "Laminado anti-UV", "5cm", "Incluido gratis con cada pedido"],
    category: "Stickers",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/stickers/sticker_wolfmoon.png",
    photoOverride: "sticker-wolfmoon-gift",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p66",
    slug: "grizzly-river-bear",
    name: "Grizzly River",
    band: "GRIZZLY RIVER",
    backBand: "GRIZZLY RIVER",
    tourYear: "",
    editionLabel: "Edición Limitada",
    price: 40,
    description:
      "Pieza de gama alta de tirada corta y numerada. Logo pequeño de garra al pecho, ilustración protagonista a la espalda con tratamiento serigrafía de gira envejecida (medio tono, tinta craquelada) en algodón pesado.",
    descriptionEn:
      "High-end limited numbered drop. Small claw logo on the chest, a protagonist illustration screen-printed on the back with an aged tour-tee treatment (halftone, cracked ink) on heavyweight cotton.",
    details: lifestyleDetails,
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [inkBlack],
    graphic: "landscape",
    artworkImage: "/artwork/print-ready/grizzly-river-front.png",
    backArtworkImage: "/artwork/print-ready/grizzly-river-back.png",
    frontLogoOnly: true,
    backTextBaked: true,
    tagline: "EDICIÓN LIMITADA · NUMERADA",
    logoStyle: { accentColor: "#e7d9b8" },
    tourDates: [],
    isNew: true,
    visible: false,
  },
  {
    id: "p67",
    slug: "howl-trucker-cap",
    visible: false,
    name: "Gorra Trucker HOWL",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Colección",
    price: 24.95,
    description:
      "Gorra trucker de espuma y malla trasera, visera curva. Parche bordado del lobo aullando a la luna al frente, con textura de hilo real — no es un estampado plano.",
    descriptionEn:
      "Foam-front trucker cap with mesh back, curved bill. Embroidered howling-wolf-and-moon patch on the front, with real thread texture — not a flat print.",
    details: [
      "Panel frontal de espuma, trasera de malla transpirable",
      "Visera curva, cierre de broches ajustable, talla única",
      "Parche bordado, no impreso — textura de hilo real",
    ],
    category: "Accesorios",
    sizes: ["Única"],
    colors: [inkBlack],
    graphic: "landscape",
    photoOverride: "howl-trucker-cap",
    logoStyle: { accentColor: "#a8452a" },
    tourDates: [],
    isNew: true,
  },
  {
    id: "p68",
    slug: "howl-brasil",
    visible: false,
    name: "HOWL Brasil",
    band: "HOWL",
    tourYear: "",
    editionLabel: "Edición Limitada",
    price: 44.95,
    description:
      "Homenaje a las camisetas de fútbol sudamericanas de los años 70. Amarelo ouro envejecido, cuello y puños de canalé, escudo bordado del lobo y wordmark HOWL serigrafiado con tratamiento craquelado. Construcción real de jersey, no camiseta básica.",
    descriptionEn:
      "A tribute to 1970s South American football shirts. Aged amarelo ouro, ribbed collar and cuffs, embroidered wolf crest and a cracked-ink screen-printed HOWL wordmark. Real jersey construction, not a basic tee.",
    details: [
      "Cuello y puños de canalé grueso, tres franjas verde/azul/amarillo",
      "Escudo bordado del lobo aullando, no estampado plano",
      "Wordmark HOWL serigrafiado con tratamiento craquelado envejecido",
      "Etiqueta tejida cosida en el bajo",
    ],
    category: "Camisetas",
    sizes: tourTeeSizes,
    colors: [{ name: "Amarelo Ouro", hex: "#e9b239" }],
    graphic: "landscape",
    photoOverride: "howl-brasil-front",
    backHeroPhoto: "howl-brasil-back",
    logoStyle: { accentColor: "#2f6b45" },
    tourDates: [],
    isNew: true,
  },
];

export function getAllProducts(): Product[] {
  return products;
}

// Orden curado a mano por atractivo/potencial de venta, de más a menos.
const FEATURED_ORDER = [
  "answer-the-call-wolf",
  "wild-west-cowboy",
  "stampede-bison",
  "answer-the-call-hoodie",
  "howl-hoodie-logo",
];

/** Productos navegables en catálogo/inicio (excluye los ocultos por stock reducido temporal). */
export function getVisibleProducts(): Product[] {
  return products.filter((p) => p.visible !== false);
}

export function getNewProducts(limit = 12): Product[] {
  return getVisibleProducts()
    .filter((p) => p.isNew)
    .slice()
    .reverse()
    .slice(0, limit);
}

export function getFeaturedProducts(): Product[] {
  return FEATURED_ORDER.map((slug) => products.find((p) => p.slug === slug)).filter(
    (p): p is Product => Boolean(p && p.visible !== false)
  );
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return getVisibleProducts()
    .filter((p) => p.id !== product.id && p.category === product.category)
    .slice(0, limit);
}

export function getCategories(): Product["category"][] {
  return Array.from(new Set(getVisibleProducts().map((p) => p.category)));
}
